language: cpp

compiler:
  - gcc
  - clang

before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; sudo apt-get update && sudo apt-get install -y libgsl0ldbl libgsl0-dev swig python-pip g++-4.8; sudo pip install sphinx breathe; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update; brew install gsl; brew install swig; brew install doxygen; brew install python-pip; sudo pip install sphinx breathe; fi
  - if [ $CXX == "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then export LD_LIBRARY_PATH=./lib:$LD_LIBRARY_PATH; fi

install: make gamera gappa tutorial1

script: bin/TutorialLevel1 docu/turorial/TutorialLevel1Params.data

os:
  - linux
  - osx
